# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1907f4fa-ec4d-4c54-b852-5048413850e0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e2586e16-fea3-4c91-b9ec-0c99273ee8a8".device = "/dev/disk/by-uuid/e2586e16-fea3-4c91-b9ec-0c99273ee8a8";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/5453-5252";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/969b4f88-b4a4-4ec1-8b98-8cdd3fd9b60c"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
